27.10
Winststreloc/MyBestProj pull request #2
Opened 2022-10-28 21:52 UTC by Winststreloc

i use my proj, with which i learn web api, i think add automapper for create function

2022-10-31 18:03 UTC, im-mrogachevskiy commented
Across all application use GUID as ID, never use int

2022-10-31 18:12 UTC, im-mrogachevskiy requested changes

2022-10-31 18:12 UTC, im-mrogachevskiy commented on 27.10/PokemonAPI/appsettings.json
> +    "DefaultConnection": "Data Source=WINST;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False"},
do not commit connection strings 
create your own appsettings.Local.json, add it to gitignore and use Local as env in launchsettings

2022-10-31 18:12 UTC, im-mrogachevskiy commented on 27.10/PokemonAPI/Data/DataContext.cs
> +    public class DataContext : DbContext
DbContext name should have 'DbContext' postfix and business domain as prefix
In your case proper name would be PokemonDbContext

2022-10-31 18:12 UTC, im-mrogachevskiy commented on 27.10/PokemonAPI/Controllers/PokemonController.cs
> +    [HttpGet("{pokemonId}")]
pokemonId:int

Always use uri parameter constraints unless it is string

2022-10-31 18:12 UTC, im-mrogachevskiy commented on 27.10/PokemonAPI/Controllers/PokemonController.cs
> +    public IActionResult GetPokemon(int pokemonId)
[FromRoute]

2022-10-31 18:12 UTC, im-mrogachevskiy commented on 27.10/PokemonAPI/Controllers/PokemonController.cs
> +            return BadRequest(ModelState);
It is GET, modelState cannot be invalid

2022-10-31 18:12 UTC, im-mrogachevskiy commented on 27.10/PokemonAPI/Controllers/PokemonController.cs
> +        [FromQuery] int pokemonId,[FromQuery] string pokemonName)
all parameters of pokemon should be from body

2022-10-31 18:12 UTC, im-mrogachevskiy commented on 27.10/PokemonAPI/Controllers/PokemonController.cs
> +            Id = pokemonId,
Usually we do not get id of new object from client. Either we create in controller or it should be generated by DB

2022-10-31 18:12 UTC, im-mrogachevskiy commented on 27.10/PokemonAPI/Controllers/PokemonController.cs
> +    public IActionResult UpdatePokemon([FromQuery] int pokemonId,[FromQuery] string pokemonName)
Pass pokemonId as URL parameter. [FromRoute]

2022-10-31 18:12 UTC, im-mrogachevskiy commented on 27.10/PokemonAPI/Controllers/PokemonController.cs
> +        var pokemonCreate = new Pokemon()
fix copypaste

2022-10-31 18:12 UTC, im-mrogachevskiy commented on 27.10/PokemonAPI/Repository/PokemonRepository.cs
> +        _context.Add(pokemonOwner);
why do you create any other entities except of pokemon?

2022-10-31 18:12 UTC, im-mrogachevskiy commented on 27.10/PokemonAPI/Repository/PokemonRepository.cs
> +        _context.Add(pokemonCategory);
same here

2022-10-31 18:12 UTC, im-mrogachevskiy commented on 27.10/PokemonAPI/Repository/PokemonRepository.cs
> +    }
_context.SaveChanges()

2022-10-31 18:12 UTC, im-mrogachevskiy commented on 27.10/PokemonAPI/Repository/PokemonRepository.cs
> +    }
_context.SaveChanges()

2022-10-31 18:12 UTC, im-mrogachevskiy commented on 27.10/PokemonAPI/Repository/PokemonRepository.cs
> +    }
_context.SaveChanges()

2022-11-02 19:15 UTC, im-mrogachevskiy requested changes
In general, this is getting better
after comments fixed that will be a very good project
I didn't check DB schema and repo but please USE GUIDS
Good job!

2022-11-02 19:15 UTC, im-mrogachevskiy commented on 27.10/PokemonAPI/Controllers/PokemonController.cs
> +
always use {} for 'if' and any other dependent block of code

2022-11-02 19:15 UTC, im-mrogachevskiy commented on 27.10/PokemonAPI/Controllers/PokemonController.cs
> +        if (!ModelState.IsValid) return BadRequest(ModelState);
what do you validate here?
there's no model to validate

2022-11-02 19:15 UTC, im-mrogachevskiy commented on 27.10/PokemonAPI/Controllers/PokemonController.cs
> +        _pokemonRepository.CreatePokemon(ownerId, categoryId, pokemon);
very good

2022-11-02 19:15 UTC, im-mrogachevskiy commented on 27.10/PokemonAPI/Controllers/PokemonController.cs
> +    public IActionResult UpdatePokemon([FromRoute] int pokemonId, [FromRoute] string pokemonName)
always get data from body
yes, in this case data is just string, but anyway it's better to create new dto class with just this string and use this dto to get data from body

REMEMBER: route is ALWAYS used just to navigate to the recourse, all the data for the resource must be in body

2022-11-02 19:15 UTC, im-mrogachevskiy commented on 27.10/PokemonAPI/Data/DbContext.cs
> +public class DbContext : Microsoft.EntityFrameworkCore.DbContext
PokemonDbContext

2022-11-02 19:15 UTC, im-mrogachevskiy commented on 27.10/PokemonAPI/Repository/PokemonRepository.cs
>      }
remove and just use _context.SaveChanges(); everywhere

2022-11-02 21:44 UTC, merged

2022-11-02 22:54 UTC, Sardle commented
You are popusk and daun